version: '3.5'

services:
  frontend:
    build: &monorepo_build
      context: .
    image: &monorepo_image monorepo-blog-standard
    container_name: frontend
    healthcheck: &monorepo_healthcheck
      test: ['CMD', 'curl', '-fs', 'http://localhost:8000/health-check']
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:  &monorepo_envs
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: &mysql_database blog
      DB_USERNAME: &mysql_user test
      DB_PASSWORD: &mysql_pass pass
      APP_KEY: "base64:7u32uk/JWO7CGLkWqD6QMecVS0DyqBWCX7keFTxEElU="
      LOG_CHANNEL: stderr
      MONOREPO_PROVIDER: App\Frontend\MonorepoProvider
    networks: &networks
      - monorepo
  backend:
    build: *monorepo_build
    container_name: backend
    image: *monorepo_image
    healthcheck: *monorepo_healthcheck
    ports:
      - '8002:8000'
    depends_on: &monorepo_depends_on
      - frontend
    environment:
      <<: *monorepo_envs
      MONOREPO_PROVIDER: App\Backend\MonorepoProvider
    networks: *networks
  chores:
    image: *monorepo_image
    depends_on: *monorepo_depends_on
    healthcheck:
      <<: *monorepo_healthcheck
      test: ['CMD', '/var/www/artisan', 'app:health-check']
    container_name: chores
    command: cron
    environment:
      <<: *monorepo_envs
      MONOREPO_PROVIDER: App\Chores\MonorepoProvider
    networks: *networks
  db:
    image: mariadb:10-focal
    container_name: db
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: test_pass
      MYSQL_USER: *mysql_user
      MYSQL_PASSWORD: *mysql_pass
      MYSQL_DATABASE: *mysql_database
    expose:
      - 3306
      - 33060
    networks: *networks
networks:
  monorepo:
