#!/usr/bin/env bash

set -e

example=$1
action=$2

provider_prefix=
laravel_dir="."

if [[ $example = "standard" ]]; then
    provider_prefix="App\\"
elif [[ $example = "non-standard" ]]; then
    laravel_dir="laravel"
else
    echo "Unknown example \"$example\""
    exit 1
fi

if [[ $action = "test" ]]; then
    cd $example/$laravel_dir
    composer test
    exit 0
elif [[ $action = "install" ]]; then
    cd $example/$laravel_dir
    composer install
    exit 0
fi

## set envs required for docker compose
export MONOREPO_PROVIDER_PREFIX="$provider_prefix"
export COMPOSE_PROJECT_NAME="demo-monorepo-$example"
export MONOREPO_LARAVEL_IMAGE_NAME="laravel-blog-$example"
export MONOREPO_SOURCE_DIR="$example/"
export MONOREPO_LARAVEL_DIR="$laravel_dir"

if [[ $action = "up" ]]; then
    docker-compose up -d
elif [[ $action = "down" ]]; then
    docker-compose down -v
elif [[ $action = "logs" ]]; then
    docker-compose logs -f
elif [[ $action = "build" ]]; then
    docker-compose rm -vsf
    docker-compose down -v --remove-orphans
    docker-compose build
    docker-compose up -d
else
    echo "Unknown action \"$action\""
    exit 1
fi

exit 0
